### ISSUE TITLE
Non String JsonProperty for Id does'nt work

### ISSUE THREAD

**Issue by johnkattenhorn** [Crokus/documentdb-repo#1]
Consider the following POCO

```
public class Foo
{
    [JsonProperty(PropertyName = "id")]
    public Guid MessageUid { get; set; }
}
```

Using this POCO throw's an exception at the line :+1: 
    var exp = Expression.Lambda<Func<T, string>>(body, p);

I'm currently learning and researching lamba's as I don't expression building very well but any help would be most welcome.

**Comment by Crokus** [comment]
Thanks for submitting issue. I've added support for non-string Id types. Let me know if it works for you.
