### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by madebysoren** [Crokus/documentdb-repo#4]
Hi,

Your project looks very good. Is it available as a Nuget package?

Best,

Søren

**Comment by Crokus** [comment]
Hi,

Thanks. The project is not available as a Nuget package. You have to clone it, build and create it by yourself.

Br,
Marcin

**Comment by Crokus** [comment]
@madebysoren made a package available on nuget.org. Check it on https://www.nuget.org/packages/DocumentDB.Repository/1.0.0

**Comment by madebysoren** [comment]
Coool @Crokus. I think a lot of people will benifit from that. I ditched DocumentDB due to its pricing though, so ended up going for a slightly different approach. Thanks though. Will keep it in mind in future projects.
