### ISSUE TITLE
Nuget Package update

### ISSUE THREAD

**Issue by neil445** [Crokus/documentdb-repo#9]
Hi there. I really love this library.
I'm using the 1.1.0 Nuget Package version and it doesn't seem to include the Interface for DocumentDbRepository yet. Any plans to update the Nuget package? Thanks a lot!

**Comment by Crokus** [comment]
Hi @neil445,

Glad you love it :) Package updated to 1.2.0.

**Comment by neil445** [comment]
Hi Crokus, isn't time to update the nuget package? I sound like I'm asking too much now. haha.

Thanks.
